_core:
  default_config_hash: SQxxJIZXuKPvJBBY6_EQCM940iKYgW6QVES9iN4s5h4
title: 'Frequently Asked Questions'
description: ''
custom_breadcrumbs: true
display: questions_top
question_listing: ul
qa_mark: false
question_label: 'Q:'
answer_label: 'A:'
question_length: short
question_long_form: true
hide_qa_accordion: false
show_expand_all: false
use_teaser: false
back_to_top: 'Back to Top'
disable_node_links: false
default_sorting: DESC
use_categories: false
category_display: categories_inline
category_listing: ul
category_hide_qa_accordion: false
count: false
answer_category_name: false
group_questions_top: false
hide_child_terms: false
show_term_page_children: false
omit_vocabulary: {  }
